language: node_js
sudo: false
node_js:
  - "node"
cache:
  directories:
    - node_modules
notifications:
  email: false
before_script:
- npm install
scripts:
  - npm test
after_success: nyc report --reporter=text-lcov | coveralls